// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtwgcdhbibdqegbrsdql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0d2djZGhiaWJkcWVnYnJzZHFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NzQxMzAsImV4cCI6MjA2MDA1MDEzMH0.zbl9t8nX7Tt1R-X2t8EZk2_uZRZ9quM_85ehiXcxm9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);